//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _fortune_teller_mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [Display(Name = "Customer ID")]
        public int CusotmerID { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Age")]
        public int Age { get; set; }
        [Display(Name = "Siblings")]
        public int NumberOfSiblings { get; set; }
        public int ColorID { get; set; }
        public int BirthMonthID { get; set; }
    
        public virtual BirthMonth BirthMonth { get; set; }
        public virtual Color Color { get; set; }
    }
}
